CREATE DATABASE [Academy]
GO
USE [Academy]
GO

CREATE TABLE [Departments] (
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Financing] MONEY NOT NULL CHECK ([Financing] >= 0 ) DEFAULT 0,
	[Name] NVARCHAR(100) NOT NULL CHECK(LEN(Name) > 0) UNIQUE
);

CREATE TABLE [Faculties] (
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Dean] NVARCHAR(MAX) NOT NULL CHECK (LEN([Dean]) > 0),
	[Name] NVARCHAR(100) NOT NULL CHECK (LEN([Name]) > 0) UNIQUE
	);

CREATE TABLE [Groups] (
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(10) NOT NULL CHECK (LEN([Name]) > 0) UNIQUE,
	[Rating] INT NOT NULL CHECK ([Rating] BETWEEN 0 AND 5),
	[Year] INT NOT NULL CHECK ([Year] BETWEEN 1 AND 50)
);

CREATE TABLE [Teachers] (
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[EmploymentDate] DATE NOT NULL CHECK ([EmploymentDate] >=  '01-01-1990'),
	[IsAssistant] BIT NOT NULL DEFAULT 0,
	[IsProfessor] BIT NOT NULL DEFAULT 0,
	[Name] NVARCHAR(MAX) NOT NULL CHECK (LEN(Name) > 0),
	[Position] NVARCHAR(MAX) NOT NULL CHECK (LEN([Position]) > 0),
	[Premium] MONEY NOT NULL CHECK ([Premium] >= 0) DEFAULT 0,
	[Salary] MONEY NOT NULL CHECK ([Salary] > 0),
	[Surname] NVARCHAR(MAX) NOT NULL CHECK (LEN(Surname) > 0) 
);